#!/usr/bin/env python3
"""
Main entry point for the agent service.
Python port of the TypeScript agent service.
"""

# Load environment variables before all other imports
import os
import sys
import asyncio
import signal
from typing import Optional
import logging

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

# Import LiveKit components
from livekit.agents import (
    JobContext,
    WorkerOptions,
    cli,
    multimodal,
    stt,
    Agent,
    AgentSession,
    AudioData,
    STTData,
    TTSData,
    RoomInputOptions, # To specify room connection options for AgentSession
)
from livekit.agents.stt import SpeechEventType # Will be handled by AgentSession/Agent
from livekit.plugins import openai, deepgram

# Import local modules
from .instructions import instructions

# Define our custom agent that wraps MultimodalAgent and integrates with AgentSession
class MyAgent(Agent):
    def __init__(self, stt_plugin, tts_plugin, instructions_text: str, job_ctx: JobContext):
        super().__init__(stt=stt_plugin, tts=tts_plugin)
        self.job_ctx = job_ctx  # To access room and participant info for publishing
        self.instructions_text = instructions_text
        self.inner_agent = multimodal.MultimodalAgent(
            model=openai.realtime.RealtimeModel(
                instructions=self.instructions_text,
                voice="alloy", # This voice is for OpenAI's TTS used by RealtimeModel
                temperature=0.7,
                max_response_output_tokens=2000,
                modalities=["text", "audio"],
                turn_detection={
                    "type": "server_vad",
                    "threshold": 0.5,
                    "silence_duration_ms": 300,
                    "prefix_padding_ms": 200,
                }
            )
            # Note: We are not passing STT/TTS directly to MultimodalAgent here,
            # as the parent Agent class will handle them via AgentSession.
        )
        # Forward key events from inner_agent if needed, or handle them via parent Agent events
        self.inner_agent.on("thinking", lambda: logger.info("Inner agent is thinking..."))
        self.inner_agent.on("response", lambda response: logger.info(f"Inner agent response: {response}"))
        # Speech from inner_agent will be captured by parent Agent's TTS and emitted as "tts_speak" or handled by its TTS plugin

    async def astart(self):
        """Called when the agent is added to a session and the session starts."""
        logger.info("MyAgent started in session. Initiating conversation.")
        # Listen to speech generated by the inner_agent's TTS
        self.inner_agent.on("speech", self._handle_inner_agent_speech)
        self.inner_agent.generate_reply() # Make the agent speak first

    def _handle_inner_agent_speech(self, speech_data: TTSData):
        """Handles speech synthesized by the inner_agent's TTS and publishes it."""
        logger.info(f"Inner agent speech: {speech_data.text}")
        if self.job_ctx.room and self.job_ctx.room.local_participant:
            # speech_data here is an object, we need the text
            text_to_publish = speech_data.text
            self.job_ctx.room.local_participant.publish_transcription({
                "participant_identity": "agent",
                "track_sid": "agent-track",
                "segments": [
                    {
                        "text": text_to_publish,
                        "final": True,
                        "id": f"agent-speech-{int(asyncio.get_event_loop().time() * 1000)}",
                        "start_time": 0,
                        "end_time": 0,
                        "language": "en-US", # Assuming en-US, adjust if needed
                    },
                ],
            })
            logger.info(f"Published agent speech to frontend: {text_to_publish}")

    async def _on_stt_data(self, event: STTData):
        """Handles STT data received by the parent Agent class from AgentSession."""
        # This method is automatically called by the Agent base class when STT data arrives
        # if an STT plugin is configured.
        super()._on_stt_data(event) # Call base class method if it has any logic

        if event.type == SpeechEventType.FINAL_TRANSCRIPT and event.alternatives and len(event.alternatives) > 0:
            transcript = event.alternatives[0].text
            participant_identity = event.participant.identity if event.participant else "unknown_user"
            logger.info(f'User transcript from {participant_identity}: "{transcript}"')

            # Feed the transcription to the inner agent
            self.inner_agent.process_transcription(event)

            # Publish user transcription to the frontend
            if self.job_ctx.room and self.job_ctx.room.local_participant and event.participant:
                # Try to get track_sid from the event if available, otherwise use a placeholder
                track_sid = event.track_id if hasattr(event, 'track_id') and event.track_id else "user-track"
                
                self.job_ctx.room.local_participant.publish_transcription({
                    "participant_identity": participant_identity,
                    "track_sid": track_sid,
                    "segments": [
                        {
                            "text": transcript,
                            "final": True,
                            "id": f"user-stt-{int(asyncio.get_event_loop().time() * 1000)}",
                            "start_time": event.start_time if hasattr(event, 'start_time') else 0,
                            "end_time": event.end_time if hasattr(event, 'end_time') else 0,
                            "language": event.language if event.language else "en-US",
                        },
                    ],
                })
                logger.info(f"Published user transcript from {participant_identity} to frontend.")
        elif event.type == SpeechEventType.INTERIM_TRANSCRIPT and event.alternatives and len(event.alternatives) > 0:
            logger.info(f'User interim transcript: "{event.alternatives[0].text}"')


def check_environment_variables() -> bool:
    """
    Check for required environment variables.
    Returns True if all required variables are present, False otherwise.
    """
    if (
        not os.environ.get("LIVEKIT_URL") or
        not os.environ.get("LIVEKIT_API_KEY") or
        not os.environ.get("LIVEKIT_API_SECRET")
    ):
        logger.error(
            "LiveKit environment variables are missing. Please check your .env file."
        )
        return False

    if not os.environ.get("OPENAI_API_KEY"):
        logger.error("OPENAI_API_KEY is missing. Please check your .env file.")
        return False

    if not os.environ.get("DEEPGRAM_API_KEY"):
        logger.error("DEEPGRAM_API_KEY is missing. Please check your .env file.")
        return False

    return True


def setup_signal_handlers():
    """Set up handlers for graceful shutdown."""
    
    def signal_handler(sig, frame):
        signal_name = "SIGTERM" if sig == signal.SIGTERM else "SIGINT"
        logger.info(f"{signal_name} received, shutting down agent worker gracefully")
        sys.exit(0)
    
    signal.signal(signal.SIGTERM, signal_handler)
    signal.signal(signal.SIGINT, signal_handler)


async def agent_entry(ctx: JobContext):
    """
    Entry point for the agent. This is the equivalent of the 'entry' function
    in the TypeScript version.
    """
    try:
        room_name = ctx.job.room.name if ctx.job.room else "default_room"
        logger.info(f"Agent entry point called for room: {room_name}")

        # Initialize Deepgram STT plugin
        deepgram_stt_plugin = deepgram.STT(
            api_key=os.environ["DEEPGRAM_API_KEY"],
            model="nova-3-general",
            language="en-US",
            smart_format=True,
            punctuate=True,
            interim_results=True, # MyAgent's _on_stt_data can handle interim if needed
            endpointing_ms=250,
            filler_words=True,
            profanity_filter=False,
        )
        logger.info("Deepgram STT plugin initialized.")

        # Initialize OpenAI TTS plugin (used by the parent Agent class if configured)
        # The MultimodalAgent's RealtimeModel also has its own TTS capabilities.
        # For simplicity, we'll let MultimodalAgent handle its TTS, but MyAgent could also use this.
        openai_tts_plugin = openai.TTS(api_key=os.environ["OPENAI_API_KEY"], voice="alloy")
        logger.info("OpenAI TTS plugin initialized.")

        # Determine which instructions to use
        resolved_instructions = (
            instructions["DON"]
            if room_name and "don" in room_name.lower()
            else instructions["REIGN"]
        )

        # Create our custom agent
        my_agent = MyAgent(
            stt_plugin=deepgram_stt_plugin,
            tts_plugin=openai_tts_plugin, # MyAgent will pass this to super()
            instructions_text=resolved_instructions,
            job_ctx=ctx # Pass JobContext for accessing room/participant details
        )
        logger.info("MyAgent instance created.")

        # Create AgentSession
        # The AgentSession will use the ctx.room object from JobContext
        # to get connection details (url, token).
        # RoomInputOptions can specify auto_subscribe behavior.
        room_input_options = RoomInputOptions(auto_subscribe=RoomInputOptions.AutoSubscribe.AUDIO_ONLY)

        session = AgentSession(
            agent=my_agent,
            room=ctx.room, # Pass the Room object from JobContext
            room_input_options=room_input_options
        )
        logger.info("AgentSession created.")

        # Run the agent session
        logger.info("Starting AgentSession...")
        await session.run() # This will connect to the room and start the agent

        # Note: my_agent.astart() will be called by the session,
        # which in turn calls self.inner_agent.generate_reply()

        logger.info("AgentSession finished or an error occurred.")

    except Exception as error:
        logger.error(f"Error in agent_entry: {error}", exc_info=True)
        # Re-raise the exception so it's caught by the worker CLI if necessary
        raise


def start_agent_worker():
    """
    Start the agent worker process. Equivalent to the startAgentWorker function
    in the TypeScript version.
    """
    logger.info("Starting agent worker process...")

    if not check_environment_variables():
        sys.exit(1)

    try:
        # Debug the LiveKit configuration
        logger.info("LiveKit configuration: %s", {
            "url": os.environ.get("LIVEKIT_URL"),
            "apiKeyExists": bool(os.environ.get("LIVEKIT_API_KEY")),
            "apiSecretExists": bool(os.environ.get("LIVEKIT_API_SECRET")),
        })

        # Start the agent with the CLI - use WorkerType.ROOM
        from livekit.agents import WorkerType
        logger.info("Starting agent worker via cli.run_app...")
        cli.run_app(
            WorkerOptions(
                entrypoint_fnc=agent_entry,
                worker_type=WorkerType.ROOM,  # Use WorkerType enum
                initialize_process_timeout=60000,  # 60 seconds timeout
            )
        )
        logger.info("Agent worker process started successfully")
    except Exception as error:
        logger.error(f"Error starting agent worker: {error}")
        sys.exit(1)


if __name__ == "__main__":
    setup_signal_handlers()
    
    # Check if dev or prod mode is specified
    is_dev = (
        os.environ.get("NODE_ENV") == "development" or 
        "dev" in sys.argv
    )

    if is_dev:
        logger.info("Running agent worker in development mode")
        # Insert 'dev' command if not already in argv
        if "dev" not in sys.argv:
            sys.argv.insert(1, "dev")
    else:
        logger.info("Running agent worker in production mode")
        # Insert 'start' command if not already in argv
        if "start" not in sys.argv:
            sys.argv.insert(1, "start")

    start_agent_worker()
