/** Memory type discriminator */
export type MemoryType = 'identity' | 'user_profile' | 'fact' | 'preference' | 'session_summary';

/** Identity attribute — who Neura is */
export interface IdentityEntry {
  id: string;
  attribute: string;
  value: string;
  source: 'default' | 'user_feedback';
  sourceSessionId: string | null;
  createdAt: string;
  updatedAt: string;
}

/** User profile field — who the user is */
export interface UserProfileEntry {
  id: string;
  field: string;
  value: string;
  confidence: number;
  sourceSessionId: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Extracted fact — durable knowledge with optional vector embedding */
export interface FactEntry {
  id: string;
  content: string;
  category: 'project' | 'technical' | 'business' | 'personal' | 'general';
  tags: string[];
  sourceSessionId: string | null;
  confidence: number;
  accessCount: number;
  lastAccessedAt: string | null;
  createdAt: string;
  updatedAt: string;
  expiresAt: string | null;
  /** Phase 5b: temporal validity — when this fact became true */
  validFrom?: string;
  /** Phase 5b: temporal validity — when this fact stopped being true (null = still valid) */
  validTo?: string | null;
  /** Phase 5b: ID of the fact that replaced this one */
  supersededBy?: string | null;
  /** Phase 5b: hierarchical tag path (dot-separated, e.g. "project.neura.memory") */
  tagPath?: string;
}

/** Behavioral preference — corrections and confirmations */
export interface PreferenceEntry {
  id: string;
  preference: string;
  category: 'response_style' | 'workflow' | 'communication' | 'technical' | 'general';
  strength: number;
  sourceSessionId: string | null;
  reinforcementCount: number;
  createdAt: string;
  updatedAt: string;
}

/** Auto-generated session summary */
export interface SessionSummaryEntry {
  id: string;
  sessionId: string;
  summary: string;
  topics: string[];
  keyDecisions: string[];
  openThreads: string[];
  extractionModel: string;
  extractionCostUsd: number | null;
  createdAt: string;
}

/** Extraction job status */
export interface MemoryExtractionRecord {
  id: string;
  sessionId: string;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  memoriesCreated: number;
  error: string | null;
  startedAt: string | null;
  completedAt: string | null;
  createdAt: string;
}

/** Composite memory context assembled for system prompt injection */
export interface MemoryContext {
  identity: IdentityEntry[];
  userProfile: UserProfileEntry[];
  recentFacts: FactEntry[];
  preferences: PreferenceEntry[];
  recentSummaries: SessionSummaryEntry[];
  tokenEstimate: number;
}

/** Shape of ~/.neura/memory-backup.json */
export interface MemoryBackup {
  version: 1 | 2;
  exportedAt: string;
  identity: IdentityEntry[];
  userProfile: UserProfileEntry[];
  facts: FactEntry[];
  preferences: PreferenceEntry[];
  sessionSummaries: SessionSummaryEntry[];
  /** Phase 5b v2: entity data */
  entities?: EntityEntry[];
  entityRelationships?: EntityRelationship[];
  factEntities?: FactEntity[];
  transcriptChunks?: TranscriptChunkEntry[];
}

/** A searchable chunk of contiguous transcript entries with a vector embedding */
export interface TranscriptChunkEntry {
  id: string;
  sessionId: string;
  chunkText: string;
  startTranscriptId: number;
  endTranscriptId: number;
  createdAt: string;
  /** Embedding vector — included in backups for restore, omitted in search results */
  embedding?: number[];
}

/**
 * Work item status (task status, Phase 6b expanded).
 *
 * The enum is extended beyond Phase 6's `pending | in_progress | done |
 * cancelled | failed` with four new states that formalize the worker
 * communication protocol:
 *
 * - `awaiting_dispatch` — task fully briefed (goal + context set), awaiting
 *   user confirmation before worker dispatch
 * - `awaiting_clarification` — worker posted a clarification_request
 *   comment; blocked on user answer (distinct from `WorkerStatus.blocked_clarifying`,
 *   which is pi-session-level state)
 * - `awaiting_approval` — worker posted an approval_request for a
 *   destructive action; blocked on user yes/no
 * - `paused` — user-initiated pause; worker session may be resumable
 *
 * See docs/phase6b-task-driven-execution.md §Schema Changes for the
 * transition matrix and crash-recovery dispositions.
 */
export type WorkItemStatus =
  | 'pending'
  | 'awaiting_dispatch'
  | 'in_progress'
  | 'awaiting_clarification'
  | 'awaiting_approval'
  | 'paused'
  | 'done'
  | 'cancelled'
  | 'failed';

/** Work item priority */
export type WorkItemPriority = 'low' | 'medium' | 'high';

/**
 * Origin of a work item. `user` = human-created (voice or UI); `system_proactive`
 * = generated by Neura (calendar reminder, deadline warning); `discovery_loop`
 * = surfaced by the background discovery loop.
 */
export type TaskSource = 'user' | 'system_proactive' | 'discovery_loop';

/**
 * Structured context attached to a task (Phase 6b). Freeform JSON that
 * workers read to understand the goal beyond the title + description.
 */
export interface TaskContext {
  /** External references the worker may need (file paths, URLs, ticket IDs, etc.). */
  references?: string[];
  /** Hard constraints the worker must respect ("don't touch production", etc.). */
  constraints?: string[];
  /** What success looks like — checked by the worker before completion. */
  acceptanceCriteria?: string[];
  /** Paths to copy from source repo into worktree (build caches, etc.). */
  copyPaths?: string[];
  /** Additional arbitrary fields — workers interpret domain-specific keys. */
  [key: string]: unknown;
}

/** Work item — a task created by the user, the discovery loop, or Neura itself */
export interface WorkItemEntry {
  id: string;
  title: string;
  description: string | null;
  status: WorkItemStatus;
  priority: WorkItemPriority;
  dueAt: string | null;
  parentId: string | null;
  sourceSessionId: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;

  // Phase 6b fields
  /** User's stated success condition, distinct from free-form description. */
  goal: string | null;
  /** Structured context for the worker. */
  context: TaskContext | null;
  /** Skill names to load as reference documentation at worker dispatch. */
  relatedSkills: string[];
  /** Absolute path to user repo (for git-worktree-based dispatch). */
  repoPath: string | null;
  /** Branch to base the git worktree on. Defaults to HEAD when dispatched. */
  baseBranch: string | null;
  /** FK to `workers.worker_id` once dispatched. */
  workerId: string | null;
  /** Origin of the task. */
  source: TaskSource;
  /** Optimistic-lock counter; incremented on every update_task. */
  version: number;
  /** Worker's heartbeat-refreshed lease. Null when not in a running class. */
  leaseExpiresAt: string | null;
}

/**
 * Type of comment posted on a task (Phase 6b). Maps to worker-protocol verbs
 * plus orchestrator/user/system responses.
 */
export type TaskCommentType =
  | 'progress' // worker progress update
  | 'heartbeat' // worker keepalive (pruned after next same-worker comment)
  | 'clarification_request' // worker asks user a question
  | 'approval_request' // worker asks user yes/no for destructive action
  | 'clarification_response' // orchestrator relays user's answer
  | 'approval_response' // orchestrator relays user's yes/no
  | 'error' // worker hit an exception or hard failure
  | 'result' // worker completed; summary of outcome
  | 'system' // system-generated (migration markers, admin actions)
  | 'deferred'; // user said "come back to this later"

/**
 * Comment author. Worker comments carry the worker id inline
 * (e.g. `worker:7f3a...`) so the audit trail survives worker churn.
 */
export type TaskCommentAuthor = string; // 'worker:<workerId>' | 'orchestrator' | 'user' | 'system'

/** Urgency on `*_request` comments. Drives queue order + critical-interrupt behavior. */
export type TaskCommentUrgency = 'low' | 'normal' | 'high' | 'critical';

/** Comment on a work item (Phase 6b). See docs/phase6b-task-driven-execution.md. */
export interface TaskCommentEntry {
  id: string;
  taskId: string;
  type: TaskCommentType;
  author: TaskCommentAuthor;
  content: string;
  /** Optional path to an attachment file when content exceeds the 32 KB cap. */
  attachmentPath: string | null;
  urgency: TaskCommentUrgency | null;
  metadata: Record<string, unknown> | null;
  createdAt: string;
}

/** Output from the extraction pipeline */
export interface ExtractionResult {
  facts: {
    content: string;
    category: string;
    tags: string[];
    tagPath?: string;
    /** Phase 5b: entity names mentioned in this fact (for precise fact-entity linking) */
    mentionedEntities?: string[];
  }[];
  preferences: { preference: string; category: string }[];
  userProfile: { field: string; value: string }[];
  identityUpdates: { attribute: string; value: string }[];
  sessionSummary: {
    summary: string;
    topics: string[];
    keyDecisions: string[];
    openThreads: string[];
  };
  /** Phase 5b: extracted entities and relationships */
  entities?: {
    name: string;
    type: 'person' | 'project' | 'tool' | 'company' | 'concept';
    relationships: { target: string; relationship: string }[];
  }[];
}

// --- Phase 5b types ---

/** Retrieval strategy for memory recall */
export type RetrievalStrategy = 'vector-only' | 'hybrid' | 'hybrid-rerank';

/** Per-tier token budgets for system prompt assembly */
export interface MemoryTierConfig {
  l0Budget: number;
  l1Budget: number;
  l2Budget: number;
}

/** Entity — a person, project, tool, company, or concept mentioned in facts */
export interface EntityEntry {
  id: string;
  name: string;
  type: 'person' | 'project' | 'tool' | 'company' | 'concept';
  canonicalName: string;
  createdAt: string;
}

/** Relationship between two entities with temporal validity */
export interface EntityRelationship {
  id: string;
  sourceEntityId: string;
  targetEntityId: string;
  relationship: string;
  validFrom: string;
  validTo: string | null;
  sourceFactId: string | null;
  createdAt: string;
}

/** Junction linking a fact to the entities it mentions */
export interface FactEntity {
  factId: string;
  entityId: string;
}

/** Timeline event for chronological queries */
export interface TimelineEntry {
  type: 'fact_created' | 'fact_invalidated' | 'entity_created' | 'relationship_created';
  timestamp: string;
  content: string;
  entityName?: string;
  factId?: string;
}

/** Aggregate memory statistics */
export interface MemoryStats {
  totalFacts: number;
  activeFacts: number;
  expiredFacts: number;
  topCategories: Record<string, number>;
  totalEntities: number;
  totalRelationships: number;
  oldestFact: string | null;
  newestFact: string | null;
  totalTranscriptsIndexed: number;
  storageEstimate: string;
}
